---
abstract: 'Inheritable, overridable, translucent class data / object attributes'
author:
  - 'Ryan McGuigan, Steve Hay <shay@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
  base: '0'
  constant: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Data-Inheritable-Translucent
no_index:
  directory:
    - t
    - inc
optional_features:
  podtest:
    description: 'POD testing'
  subname:
    description: 'Naming subroutines in caller() messages etc.'
    recommends:
      Sub::Name: '0'
requires:
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/steve-m-hay/Class-Data-Inheritable-Translucent.git
version: '1.03'
